/**
 * Welcome to Cloudflare Workers! This is your first worker.
 *
 * - Run "npm run dev" in your terminal to start a development server
 * - Open a browser tab at http://localhost:8787/ to see your worker in action
 * - Run "npm run deploy" to publish your worker
 *
 * Learn more at https://developers.cloudflare.com/workers/
 */

// export default {
//   async fetch(request, env, ctx) {
//     // You can view your logs in the Observability dashboard
//     console.info({ message: 'Hello World Worker received a request!' });
//     return new Response('Hello World!');
//   }
// };

export default {
async fetch(request, env, ctx) {
	console.info({ message: 'Serving an HTML page!' });

	// 1. Create your HTML content as a string
	const htmlContent = `
	<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>My Cloudflare Worker</title>
		<style>
		body {
			font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
			background-color: #f4f6f8;
			display: flex;
			justify-content: center;
			align-items: center;
			height: 100vh;
			margin: 0;
			color: #333;
		}
		.card {
			background-color: white;
			padding: 40px;
			border-radius: 12px;
			box-shadow: 0 4px 12px rgba(0,0,0,0.1);
			text-align: center;
		}
		h1 {
			color: #f38020; /* Cloudflare Orange */
			margin-top: 0;
		}
		</style>
	</head>
	<body>
		<div class="card">
		<h1>Hello test...?!</h1>
		<p>This page is being generated by a Cloudflare Worker.</p>
		</div>
	</body>
	</html>
	`;

	// 2. Return the HTML with the correct headers
	return new Response(htmlContent, {
	headers: {
		"Content-Type": "text/html;charset=UTF-8",
	},
	});
}
};
